# Generated by Django 5.2 on 2025-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='試験日')),
                ('mix_name', models.CharField(max_length=200, verbose_name='配合名')),
                ('mix_amount_1', models.FloatField(verbose_name='配合量1')),
                ('mix_amount_2', models.FloatField(verbose_name='配合量2')),
                ('test_result', models.FloatField(verbose_name='試験結果')),
            ],
            options={
                'verbose_name': '実験データ',
                'verbose_name_plural': '実験データ',
                'ordering': ['-test_date'],
            },
        ),
    ]
